// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKA3uBSfVL5sYw8w9rd61X2BiZ2J_Ngws',
    appId: '1:234873274464:web:c5ee93575cefaad1a94305',
    messagingSenderId: '234873274464',
    projectId: 'motorcycle-clinic',
    authDomain: 'motorcycle-clinic.firebaseapp.com',
    storageBucket: 'motorcycle-clinic.appspot.com',
    measurementId: 'G-3XY3F4LQEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXG22U58jBE2Pr8WCtgXFVxw2xzqml89A',
    appId: '1:234873274464:android:620c155b89dd70fca94305',
    messagingSenderId: '234873274464',
    projectId: 'motorcycle-clinic',
    storageBucket: 'motorcycle-clinic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgtIfBhrq6cM831NVICUWNfuJMeEt8hyU',
    appId: '1:234873274464:ios:be664b4ee47f1a1fa94305',
    messagingSenderId: '234873274464',
    projectId: 'motorcycle-clinic',
    storageBucket: 'motorcycle-clinic.appspot.com',
    iosClientId: '234873274464-7p9mccv0ogovtvb6tguuth2csspjqcim.apps.googleusercontent.com',
    iosBundleId: 'com.example.motorcycleClinicMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgtIfBhrq6cM831NVICUWNfuJMeEt8hyU',
    appId: '1:234873274464:ios:be664b4ee47f1a1fa94305',
    messagingSenderId: '234873274464',
    projectId: 'motorcycle-clinic',
    storageBucket: 'motorcycle-clinic.appspot.com',
    iosClientId: '234873274464-7p9mccv0ogovtvb6tguuth2csspjqcim.apps.googleusercontent.com',
    iosBundleId: 'com.example.motorcycleClinicMobile',
  );
}
